setup.py
tx
txclib/__init__.py
txclib/web.py

@amanatidis Please, take a look.

Use valid versioning format

---

README.rst
txclib/parsers.py
txclib/project.py
txclib/utils.py

@diegobz I have fixed the links, I created some new bit.ly so they are easy to be c/p from users. Please review and merge.

Links pointing to Transifex documentation fixed

---

appveyor.yml
contrib/test_win_build.sh
contrib/tx.spec
contrib/tx_commands.sh
setup.py
tox.ini
txclib/__main__.py
txclib/cmdline.py

PR #105 skips the integration tests for every build of a pull request regardless if the person who pushed was a project developer or not. I added a commit here to do so only when the `TRANSIFEX_USER` isn't there, since the project developers might want to open a PR themselves. cc @diegobz

Addendum to PR #105

---

tests/test_project.py
txclib/cmdline.py
txclib/commands.py
txclib/config.py
txclib/parsers.py
txclib/project.py
txclib/utils.py

@diegobz I know it's huge PR and of less significance than others. I'll leave it here just in case.

Fixes to comply with PEP8

---

tests/test_utils.py
txclib/project.py
txclib/utils.py

Description: Look at title.
Jira ticket: https://transifex.atlassian.net/browse/TX-5919

Fix issues with zip type formats (docx, xlsx).

---

txclib/commands.py
txclib/project.py
txclib/utils.py

support standard tx urls

---

contrib/tx_commands.sh
requirements.txt
txclib/commands.py
txclib/config.py
txclib/project.py
txclib/utils.py

use input from six.moves. Fixes: #123

---

README.md
README.rst
appveyor.yml
codecov.yml
tox.ini

Codecov & AppVoyer improvements

---

codecov.yml

@diegobz Hide codecov-slack webhook

Hide codecov-slack webhook

---

txclib/utils.py

If you pass mixed unicode and str arguments (say, a unicode URL and a
binary file that can't be encoded by *any* encoding), at some point
urllib3 will try to concaternate them to unicode and fail.
This implements a decorator that recursively encodes all arguments from
unicode to str. I apply this decorator to the only `request` call from
urllib3 that I could find in the codebase.

[DNM] Always pass bytes (type str) to urllib3 request calls

---

contrib/tx_commands.sh
txclib/project.py

Making client compatible with the updated API endpoint for uploading as xliff.
cc: @kbairak

make client compatible with updated api xliff endpoint

---

contrib/tx_commands.sh

Upload translations for target language explicitly. Re-introduce xliff tests.

modify intergration test

---

txclib/exceptions.py
txclib/project.py

@ChrsMark can you pls review?
relates to these two issues: 
* https://github.com/transifex/transifex-client/issues/146
* https://github.com/transifex/transifex-client/issues/139

Improve error messages

---

txclib/project.py

Related story: [TX-8606](https://transifex.atlassian.net/browse/TX-8606).

TX-8606 Change auto-remote setup handling when no extension found

---

tests/test_project.py
txclib/project.py
txclib/urls.py

Related story [TX-7017](https://transifex.atlassian.net/browse/TX-7017)

TX-7017 Enable pull mode sourceastranslation

---

txclib/config.py
txclib/project.py

These are some simple changes in the wording of some exception and info messages.

Update some logger messages to be more descriptive

---

contrib/tx_commands.sh
requirements.txt
tests/test_api.py
tests/test_commands.py
tests/test_project.py
tests/test_wizard.py
tox.ini
txclib/api.py
txclib/commands.py
txclib/messages.py
txclib/parsers.py
txclib/project.py
txclib/urls.py
txclib/utils.py
txclib/wizard.py

Interactive wizard for tx client.
Main points:
* A new field `api_hostname` has been added to the transifexrc file. In order for this to be transparent for the user it get's `https://api.transifex.com` as the default value. For development purposes this field should be manually edited in the file. There is also a mapping of api calls to either `hostname` or `api_hostname` in order to know which hostname to use in the request.
* Implement new Api class to perform requests both to new and old api endpoints required for the interactive wizard.
* Use https://github.com/magmax/python-inquirer to handle interactive input for the user
* Move some of the Project functions related to  to utils.py since they don't require a project instance to run

Interactive wizard

---

txclib/__init__.py

In this version:
* Python 3 compatibility fixes
* Enable support for Python 3.6

Bump version to 0.13.1

---

contrib/tx_commands.sh
tests/test_commands.py
tests/test_project.py
txclib/commands.py
txclib/parsers.py
txclib/project.py
txclib/utils.py

Allow the parallelization of the requests with `push` or `pull` commands. You can enable this option by adding the `--async` flag.

Parallel push pull

---

tests/test_commands.py
tests/test_utils.py
txclib/commands.py
txclib/project.py
txclib/utils.py

Optimize the way we handle regular expressions that are used to match translations files. This is intended to improve the commands' performance.

Optimize regular expression handling

---

.circleci/config.yml
setup.py
tox.ini

Only test latest 2.X and 3.X versions in CircleCI

Support Python 3.4

---

appveyor.yml
contrib/tx_commands.sh

Various updates on appveyor.yml file including:
* Comments and changes based on the latest reference
* Define Appveyor version
* Build for Python 3.7
* Don't pin pip to an older version
The changes were based on the following resources:
- https://www.appveyor.com/docs/appveyor-yml/  (appveyor yaml reference)
- https://www.appveyor.com/docs/lang/python/   (using python stack in appveyor)
- https://packaging.python.org/guides/supporting-windows-using-appveyor/
- https://github.com/ogrisel/python-appveyor-demo
Also this PR fixes via a hack a random occuring error on the tests conducted by ```contrib/tx_commands.sh``` script. The error occurs either on the CircleCI build or the Appveyor builds in the last command of the script that deletes a resource:
```
tx INFO: Deleting resource …
```

Update appveyor settings plus fix txci tests random error on resource delete 

---

tests/test_utils.py
txclib/utils.py

*This PR continues on PR [#264](https://github.com/transifex/transifex-client/pull/264) which had failing CircleCI tests (because environment variables are not being copied across forked repositories).*
We fix retrieving http proxy environment variables either if they are set via:
```
export http_proxy="host:port"
export https_proxy="host:port"
```
or when we unset them via:
```
unset http_proxy
unset https_proxy
```
or via:
```
export http_proxy=""
export https_proxy=""
```
How to test
------------
Install locally or use a proxy server. (MacOs users can easily install [SquidMan](https://squidman.net/squidman/index.html) that installs locally Squid proxy). Then set/unset http proxy variables and test transifex-client functioning while also keeping an eye on the proxy log (when proxy …

Fixed bug retrieving http proxy values from environment variables

---

README.md
setup.py

We are pointing to the wrong repo in the README file.

Fix README link to Issues

---

txclib/__init__.py

Should update the version number for the next release.

Bump release version

---

txclib/__init__.py

Merged PRs:
* #324 Change download path when supplied language is source language

Bumps version to 0.14.3
