README.rst

Looks like this link hasn't been updated in awhile.

Fix documentation link in README

---

txclib/utils.py

This pull request fixes a problem with symbolic links when the project contains symbolic links that enter infinite loops. For example a user can specify a symbolic link in the project directory that links to the project directory itself.
@diegobz Please review and merge.

Fix symbolic link loops during os.walk

---

appveyor.yml
contrib/test_win_build.sh
contrib/tx.spec
contrib/tx_commands.sh
setup.py
tox.ini
txclib/__main__.py
txclib/cmdline.py

This makes `tx` work right out of the box when you `pip install transifex-client` on Windows.

Use entry_points instead of scripts for cross-platform compatibility

---

tests/test_utils.py
txclib/exceptions.py
txclib/project.py
txclib/utils.py

In some cases Transifex API returns 401 (Not Authorized) which currently raises Exception without providing any extra information for the user. It makes it hard to investigate why push or pull is not happening as expected.
I'm adding a new HTTP exception class + extra logging.

Handle HTTP exception 401

---

tests/test_utils.py
tox.ini
txclib/utils.py

A working version of the Transifex client with added support for proxies. To use, set the http_proxy and https_proxy environment variables. @kouk

Support for proxies 

---

tox.ini

@tabac & @kouk codecov token is not needed, because client is public repo. Also it prevents forked branches to be merged.

Remove token, not used in public repos

---

txclib/project.py

This commit https://github.com/transifex/transifex-client/commit/1eae96b4409fd248207e879abda4e1703610a992 broke pushing of .po files as it blindly sets xliff to `True` instead of reading the parameter sent to the function.
If you try to push a .po file with with the current client you will stumble upon the error message:
`Skipping '<LANG>' translation (file: <PATH><FILE>.po.xlf).` even if you have not set the -x/--xliff flag in your push command.

Use xliff parameter when getting resource files on push

---

contrib/tx_commands.sh
txclib/project.py

While trying to push translations to Transifex for a set of resources, if one of the resources didn't have a translation file yet in the repo/locally, the push out abort with an exception.

Don't break if on translation push a file is not available locally

---

tests/test_utils.py
txclib/utils.py

If a user does not belong to the translation team and tries to make a tx pull,
a 403 status code is returned.
Instead of just displaying "Exception", gives a bit more context on the failure

[FIX] raise HttpNotAuthorized for 403 errors

---

tests/test_commands.py
txclib/cmdline.py
txclib/commands.py
txclib/log.py
txclib/project.py

Throw error in the following cases:
- when user calls tx pull and the project is not initialized
- When the given command is not found an 1 error code will be returned
Also, add error level information on logger output.
Related issue #186

TX-8362 Return non-zero exit code on errors

---

tests/test_commands.py
txclib/commands.py

**Problem**
We recently updated the logger formatter to add a prefix in all its output (see [here](https://github.com/transifex/transifex-client/pull/186/files#diff-c6b1be0e6471d27cf8986daf109edf37R16)). This has some side effects like the help text to be displayed like: 
```
tx INFO: Transifex command line client.
tx INFO: Available commands are:
tx INFO:   delete         	Delete an accessible resource or translation in a remote server.
tx INFO:   help           	List all available commands
tx INFO:   init           	Initialize a new transifex project.
tx INFO:   pull           	Pull files from remote server to local repository
tx INFO:   push           	Push local files to remote server
tx INFO:   set            	Add local or remote files under transifex
tx INFO:   status         	Print …
```

Don't use logger for regular output like help and status

---

tests/test_project.py
tests/test_utils.py
txclib/cmdline.py
txclib/exceptions.py
txclib/project.py
txclib/utils.py

This fixes the following problems:
* Handle connection errors gracefully and display helpful messages
* Exit with a non-zero code whenever a command fails
* Allow host to have a trailing slash
* Remove code duplicates and correctly interpret user input when the `--force` parameter is specified

TX-8917 fix various CLI bugs

---

txclib/project.py

Provide a correct error message when the user tries to push a language code that is invalid.

TX-2663: Correctly distinguish push errors

---

tests/test_commands.py
tests/test_project.py
tests/test_utils.py
txclib/commands.py
txclib/parsers.py
txclib/project.py
txclib/utils.py

Summary
---------
Adds basic support for branch in Transifex Client. `tx pull` and `tx push` now accepts two extra arguments `--branch` and `--branchname` in order to push/pull different version of the configured resources. If only the `--branch` option is pass the client tries to detect the current git branch from the filesystem and throughs an error if not under a git repo. If branchname is passed then takes precedence over the current git branch if it exists.
When the branch is specified, for each resource specified a new resource is created on Transifex with slug `<branchname>--<resource_slug>`. Translations or source content are then pushed and pulled from the resource matching that pattern.

Branch support

---

contrib/tx_commands.sh
tests/project_dir/.transifexrc
tests/test_commands.py
tests/test_wizard.py
txclib/cmdline.py
txclib/commands.py
txclib/messages.py
txclib/parsers.py
txclib/project.py
txclib/utils.py
txclib/wizard.py

* Tx set --auto-local and --auto-remote functionality is independent of one another. Having this options on the same level as all the rest of the options created confusion.  
* When trying to set a lot of local files, you need to call a `set` command for each file separately. If you have lots of files, it takes a lot of time and it's not convenient.
Create new subcommands for `tx set` command, namely `auto-local`, `auto-remote`, `bulk`. Each subcommand support it own options and positional arguments. Base `tx set` is still supported as before but only with the minimum options.
Example:
To set a series of HTML source files that reside inside `locale/`:
```
tx set bulk -p myproject 'locale/<lang>/{filepath}/{filename}{extension}' --source-language en --type HTML --file-extension '.html' -d …
```

Create new Set subcommand for multiple files and auto-local, auto-remote

---

contrib/tx_commands.sh
setup.py
tests/test_commands.py
tests/test_wizard.py
txclib/commands.py
txclib/parsers.py
txclib/wizard.py

* Make auto-local, auto-remote backwards compatible
* Limit supported Python versions 2.7, 3.5
* Update source_language field to reflect change in the API
* Make expression argument for bulk subcommand optional with a default value

Backwards compatibility, update on supported python versions

---

txclib/messages.py
txclib/wizard.py

readline is not supported in windows, so we need to handle the ImportError that is thrown if it is not available.
Also rename set --> config on some logging messages that weren't updated.

Readline compat

---

tests/test_commands.py
tox.ini
txclib/parsers.py
txclib/project.py

* Import `StringIO` from `io` module in Python 3
* Fix typo in tox.ini that was causing tests to run in Python 2.7
* Don't use `Exception.message` as it is not supported in Python 3
* Fix incompatible syntax in ArgumentParser parameters
Fixes #207

Fix some Python 3 compatibility issues

---

tests/test_commands.py
txclib/commands.py
txclib/parsers.py

Deprecate the positional argument `expression` for the `tx config mapping` command in favour of `--expression` so all sub-commands are consistent.

Add `--expression` as an argument for `tx config mapping`, so the `tx config` commands are consistent

---

txclib/utils.py

When an error happens during a request that is performed by a thread, the stack trace is printed out to the user, even if he hasn't specified the `--traceback` flag. This PR intends to change this behaviour by not raising exceptions when the error happens inside a thread.

Avoid printing stack traces within threads

---

contrib/tx_commands.sh
tests/test_commands.py
tests/test_project.py
txclib/cmdline.py
txclib/commands.py
txclib/project.py

1. don't write cleartext passwords to ~/.transifexrc. 
2. Existing configs with passwords are treated like before.
3. use TX_TOKEN environment variable as the API token if not otherwise
provided.
Example:
```
$ export TX_TOKEN=1/deadbeef...
$ tx init
_____                    _  __
|_   _| __ __ _ _ __  ___(_)/ _| _____  __
| || '__/ _` | '_ \/ __| | |_ / _ \ \/ /
| || | | (_| | | | \__ \ |  _|  __/>  <
|_||_|  \__,_|_| |_|___/_|_|  \___/_/\_\
Welcome to the Transifex Client! Please follow the instructions to
initialize your project.
tx INFO: Creating .tx folder...
<snip>
$ tx push --source
tx INFO: Pushing resource testproject.testresource-txt
tx INFO: Updating /Users/myself/.transifexrc file...
tx INFO: Pushing source file (testresource.txt)
tx INFO: Updating /Users/myself/.transifexrc …
```

 Use TX_TOKEN env var for API token

---

contrib/tx_commands.sh
tox.ini

Project slug is unique, so configuration that work with CI settings will not work locally with the developer's account. So we need to overwrite it in order integration tests to pass locally.
Currently used in `tx_commands.sh`. CI's environment will need to be updated to support $PROJECT_SLUG, with a value of 'txci'.

Add an environment variable for project slug to be used in tests.

---

appveyor.yml
tests/test_commands.py
tests/test_project.py
txclib/commands.py
txclib/project.py

Reverted changes made by previous commits which were forcing the TX_TOKEN environment variable. Now both TX_TOKEN and password in the .transifexrc file are supported.

Env token along with token argument

---

tests/test_commands.py
txclib/commands.py
txclib/parsers.py
txclib/project.py

Checklist (for the reviewer)
----------------------------
Problem
-------
Users need to use the tx pull command without user input.  This is needed in some cases where CI environments need to fail silently.
Steps to reproduce
------------------
- Make sure that TX_TOKEN is not set `unset TX_TOKEN`
- Remove any previous configuration `rm ~/.transifexrc`
- Initialize a new project `tx init --host="https://www.transifex.com" --skipsetup --no-interactive`
- Run config mapping for a resource (ex`tx config mapping -r demo_project.demo -s en 'locale/<lang>/LC_MESSAGES/django.po' -t PO --execute`)
- Run `tx pull`
- Confirm that user input is required.
Solution
--------
Add the --no-interactive argument in the tx pull command. This means that no user input will be required when no token info …

Add the no-interactive flag to the pull command

---

tests/test_wizard.py
txclib/messages.py
txclib/wizard.py

While initializing a Transifex project with the wizard, we no longer proceed if the file extension does not match any of our supported file formats.

Make the initialization wizard fail if no suitable formats are found

---

txclib/parsers.py

PR (https://github.com/transifex/transifex-client/pull/243) had failing CircleCI tests (because environment variables are not being copied across forked repositories).

Fix typo in parsers.py

---

txclib/project.py

PR https://github.com/transifex/transifex-client/pull/238 fixes an issue we had for ages, where an INFO message was treated as a WARNING, showing a warning message on every `tx pull`. The issue was introduced back in 2012 (https://github.com/transifex/transifex-client/commit/d8add0c03a2ca2f48972cd7ab54ec4c906e49bb9), probably due to copying and pasting.
The original PR was missing the ENV variables added by the CircleCI (because the user opened the PR from a forked repo) so the tests were failing.
Message from the original PR: 
Fixes #237.

Fix log level of remote lang to local path message

---

appveyor.yml
requirements.txt

Bump of urllib3 version due to security update.
```
CVE-2019-11324
More information
high severity
Vulnerable versions: < 1.24.2
Patched version: 1.24.2
The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired 
set of CA certificates is different from the OS store of CA certificates, which results in SSL
connections succeeding in situations where a verification failure is the correct outcome. 
This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.
```

Security related update for urllib3

---

.circleci/config.yml
contrib/tx_commands.sh
setup.py
tox.ini

This PR continues on PR https://github.com/transifex/transifex-client/pull/266 which had failing CircleCI tests (because environment variables are not being copied across forked repositories).

Support Python 3.8

---

requirements.txt
tests/test_utils.py

~~It also bumps `urllib3` minimum version required to `1.24.3`, as the previous versions have a security concern (CVE-2019-11324)~~. 
Actually urllib3 `1.24.2` is fine, so no minimum version bump needed.

Loosen up dependency versions

---

txclib/utils.py

Symbolic links used not to be correctly asserted in the manner of matching the user-defined regular expressions. Thus symlinking translation files into the initial set up project directory ended to translation files not being able to be uploaded.

Fix the symlink push issue

---

txclib/__init__.py
txclib/utils.py

We had an issue reported where having a symlinked directory caused a language to not be detected.
This ended up being due to having added provisions for not going into infinite loops due to symlinks.
We would visit each "real" subdirectory only once, which meant that if you have 10 directories symlinked with different names, only the first one would be picked up as a candidate and assigned the language the name pointed to. The others would be ignored.
Changed this to a max-depth approach to instead stop infinite loops this way.

Fixing a symlink issue

---

requirements.txt
tests/test_commands.py
tests/test_project.py
tests/test_utils.py
txclib/commands.py
txclib/parsers.py
txclib/project.py
txclib/utils.py

Attempt at solving #22 
We had this issue because we're running tx client inside a github action -- https://github.com/sergioisidoro/github-transifex-action --, which will clone the repository from scratch. This means the OS timestamp is always newer than the one in transifex.
This PR adds support for fetching the timestamp of a file form the last commit for that file.
TODO:

Flag for comparing file timestamp through git

---

appveyor.yml
contrib/tx.spec
requirements.txt

If merged this would solve this https://github.com/transifex/transifex-client/issues/281.
I had to upgrade pyinstaller to have the hook added in this [PR](https://github.com/pyinstaller/pyinstaller/pull/4530)  for text_unidecode a dependency of python-slugify>=2.0.0
I also changed the path since  pyinstaller>=3.5 added support for relative paths https://github.com/pyinstaller/pyinstaller/pull/3444 and the previous configuration was throwing 
```
IOError: [Errno 2] No such file or directory: 'contrib\\contrib/tx.ico'
```
You can see that in https://ci.appveyor.com/project/transifex/transifex-client/builds/33350716/job/dbs7ufhkj4ajfoy1

Bump constraint for python-slugify dependency

---

txclib/cmdline.py
txclib/parsers.py
txclib/web.py

Problem and/or solution
-----------------------
This addresses #91 
We add the option to define a private CA certificate bundle file instead of the default which is to use the system's trust store.
How to test
-----------
Test it with a local existent or not cert file like so:
```
tx pull -a --cacert /etc/ssl/certs/ca-certificates.crt
```

CLI option for custom CA certificate bundle file

---

tests/test_utils.py
txclib/utils.py

This ensures expected behaviour for rebased commits.
https://alexpeattie.com/blog/working-with-dates-in-git/

Use authored date instead of committed date as git file timestamp

---

.circleci/config.yml
requirements.txt
setup.py
tox.ini

@terencehonles has updated our transifex-client to use python3 successfully. Something did not work into our merging pipeline (appveyor) thus I created that PR as a workaround to unblock the process.

Support Python 3.9

---

txclib/parsers.py

Forgot returning the cacert path after asserting the cacert file existance.

Minor missing argument fix

---

txclib/project.py

When invoking `pull` command, with the `--language` argument supplied,
it will use the path dictated by the `file_filter` as the download
path for each language.
This behavior is not altered even when the source language is passed
and the source file is downloaded at the path dictated by `file_filter`
and the `source_file` path that is present in the configuration.
With this commit we can that the language passed is the source language
and always store the downloaded file in the `source_file` path
that is present in the configuration
Let's use an example to better illustrate the issue:
config:
```
[project_slug.resource_slug]
file_filter = locale/<lang>/ui.po
source_file = locale/ui.po
source_lang = en
type = PO
```
Existing behavior:
`tx pull --language en`
=> download path = …

Change download path when supplied language is source language

---

requirements.txt
tests/project_dir/.transifexrc
tests/test_commands.py
txclib/config.py

Patch issue 317
